// <auto-generated />
using System;
using FaciTech.Apartment.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FaciTech.Apartment.Database.Migrations
{
    [DbContext(typeof(FaciTechDbContext))]
    partial class FaciTechDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FaciTech.Apartment.Database.Models.Amenity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comments");

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("CreatedBy");

                    b.Property<bool>("Inactive");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("Updated");

                    b.Property<Guid>("UpdatedBy");

                    b.HasKey("Id");

                    b.ToTable("Amenity");
                });

            modelBuilder.Entity("FaciTech.Apartment.Database.Models.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CityId");

                    b.Property<string>("Comments");

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("CreatedBy");

                    b.Property<bool>("Inactive");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("Updated");

                    b.Property<Guid>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Area");

                    b.HasData(
                        new
                        {
                            Id = new Guid("538a9be1-25c0-4a26-a8dd-93e32937faa2"),
                            CityId = new Guid("bce5ac11-1af6-4301-86ac-83c97c218f7c"),
                            Created = new DateTime(2019, 6, 28, 18, 39, 1, 26, DateTimeKind.Utc).AddTicks(532),
                            CreatedBy = new Guid("fc3f9472-69c9-4dd3-8fab-8ba2639812f0"),
                            Inactive = false,
                            Name = "North",
                            Updated = new DateTime(2019, 6, 28, 18, 39, 1, 26, DateTimeKind.Utc).AddTicks(886),
                            UpdatedBy = new Guid("fc3f9472-69c9-4dd3-8fab-8ba2639812f0")
                        },
                        new
                        {
                            Id = new Guid("f314122a-e758-4c11-a48e-198ef276874e"),
                            CityId = new Guid("bce5ac11-1af6-4301-86ac-83c97c218f7c"),
                            Created = new DateTime(2019, 6, 28, 18, 39, 1, 26, DateTimeKind.Utc).AddTicks(1537),
                            CreatedBy = new Guid("fc3f9472-69c9-4dd3-8fab-8ba2639812f0"),
                            Inactive = false,
                            Name = "South",
                            Updated = new DateTime(2019, 6, 28, 18, 39, 1, 26, DateTimeKind.Utc).AddTicks(1542),
                            UpdatedBy = new Guid("fc3f9472-69c9-4dd3-8fab-8ba2639812f0")
                        });
                });

            modelBuilder.Entity("FaciTech.Apartment.Database.Models.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comments");

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("CreatedBy");

                    b.Property<bool>("Inactive");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<Guid>("StateId");

                    b.Property<DateTime>("Updated");

                    b.Property<Guid>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("City");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bce5ac11-1af6-4301-86ac-83c97c218f7c"),
                            Created = new DateTime(2019, 6, 28, 18, 39, 1, 25, DateTimeKind.Utc).AddTicks(8691),
                            CreatedBy = new Guid("fc3f9472-69c9-4dd3-8fab-8ba2639812f0"),
                            Inactive = false,
                            Name = "Bangalore",
                            StateId = new Guid("29d44de8-9138-4295-ad1d-486a92eb74a4"),
                            Updated = new DateTime(2019, 6, 28, 18, 39, 1, 25, DateTimeKind.Utc).AddTicks(9019),
                            UpdatedBy = new Guid("fc3f9472-69c9-4dd3-8fab-8ba2639812f0")
                        });
                });

            modelBuilder.Entity("FaciTech.Apartment.Database.Models.Community", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("AmenityIds");

                    b.Property<string>("AssociationBankAccountNumber");

                    b.Property<string>("AssociationBankBranchAddress");

                    b.Property<string>("AssociationBankIFSC");

                    b.Property<string>("AssociationBankName");

                    b.Property<string>("AssociationName");

                    b.Property<string>("AssociationNumber");

                    b.Property<string>("BuilderName")
                        .IsRequired();

                    b.Property<string>("Comments");

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("CreatedBy");

                    b.Property<bool>("Inactive");

                    b.Property<string>("Landmark");

                    b.Property<string>("LocationLink");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<Guid>("SubAreaId");

                    b.Property<DateTime>("Updated");

                    b.Property<Guid>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("SubAreaId");

                    b.ToTable("Community");
                });

            modelBuilder.Entity("FaciTech.Apartment.Database.Models.CommunityLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Area");

                    b.Property<Guid>("AreaId");

                    b.Property<string>("AssociationBankAccountNumber");

                    b.Property<string>("AssociationBankBranchAddress");

                    b.Property<string>("AssociationBankIFSC");

                    b.Property<string>("AssociationBankName");

                    b.Property<string>("AssociationName");

                    b.Property<string>("AssociationNumber");

                    b.Property<string>("BuilderName");

                    b.Property<string>("City");

                    b.Property<Guid>("CityId");

                    b.Property<string>("Country");

                    b.Property<Guid>("CountryId");

                    b.Property<string>("Landmark");

                    b.Property<string>("LocationLink");

                    b.Property<string>("Name");

                    b.Property<string>("State");

                    b.Property<Guid>("StateId");

                    b.Property<string>("SubArea");

                    b.Property<Guid>("SubAreaId");

                    b.HasKey("Id");

                    b.ToTable("CommunityLocation");
                });

            modelBuilder.Entity("FaciTech.Apartment.Database.Models.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comments");

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("CreatedBy");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<bool>("Inactive");

                    b.Property<string>("LastName");

                    b.Property<string>("MobilePhone")
                        .IsRequired();

                    b.Property<string>("Phone");

                    b.Property<DateTime>("Updated");

                    b.Property<Guid>("UpdatedBy");

                    b.HasKey("Id");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("FaciTech.Apartment.Database.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comments");

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("CreatedBy");

                    b.Property<bool>("Inactive");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("Updated");

                    b.Property<Guid>("UpdatedBy");

                    b.HasKey("Id");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bc389b83-ded4-406a-a318-0616b7973734"),
                            Created = new DateTime(2019, 6, 28, 18, 39, 1, 25, DateTimeKind.Utc).AddTicks(4799),
                            CreatedBy = new Guid("fc3f9472-69c9-4dd3-8fab-8ba2639812f0"),
                            Inactive = false,
                            Name = "India",
                            Updated = new DateTime(2019, 6, 28, 18, 39, 1, 25, DateTimeKind.Utc).AddTicks(5172),
                            UpdatedBy = new Guid("fc3f9472-69c9-4dd3-8fab-8ba2639812f0")
                        });
                });

            modelBuilder.Entity("FaciTech.Apartment.Database.Models.Feature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comments");

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("CreatedBy");

                    b.Property<bool>("Inactive");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("Updated");

                    b.Property<Guid>("UpdatedBy");

                    b.HasKey("Id");

                    b.ToTable("Feature");
                });

            modelBuilder.Entity("FaciTech.Apartment.Database.Models.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comments");

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("CreatedBy");

                    b.Property<bool>("Inactive");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("Updated");

                    b.Property<Guid>("UpdatedBy");

                    b.HasKey("Id");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("FaciTech.Apartment.Database.Models.GroupRole", b =>
                {
                    b.Property<Guid>("GroupId");

                    b.Property<Guid>("RoleId");

                    b.Property<string>("Comments");

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("CreatedBy");

                    b.Property<bool>("Inactive");

                    b.Property<DateTime>("Updated");

                    b.Property<Guid>("UpdatedBy");

                    b.HasKey("GroupId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("GroupRole");
                });

            modelBuilder.Entity("FaciTech.Apartment.Database.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comments");

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("CreatedBy");

                    b.Property<bool>("Inactive");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("Updated");

                    b.Property<Guid>("UpdatedBy");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("FaciTech.Apartment.Database.Models.RoleFeature", b =>
                {
                    b.Property<Guid>("RoleId");

                    b.Property<Guid>("FeatureId");

                    b.Property<string>("Comments");

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("CreatedBy");

                    b.Property<bool>("Inactive");

                    b.Property<DateTime>("Updated");

                    b.Property<Guid>("UpdatedBy");

                    b.HasKey("RoleId", "FeatureId");

                    b.HasIndex("FeatureId");

                    b.ToTable("RoleFeature");
                });

            modelBuilder.Entity("FaciTech.Apartment.Database.Models.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comments");

                    b.Property<Guid>("CommunityId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("CreatedBy");

                    b.Property<bool>("Inactive");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("NoOfFloors");

                    b.Property<DateTime>("Updated");

                    b.Property<Guid>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.ToTable("Section");
                });

            modelBuilder.Entity("FaciTech.Apartment.Database.Models.State", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comments");

                    b.Property<Guid>("CountryId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("CreatedBy");

                    b.Property<bool>("Inactive");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("Updated");

                    b.Property<Guid>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("State");

                    b.HasData(
                        new
                        {
                            Id = new Guid("29d44de8-9138-4295-ad1d-486a92eb74a4"),
                            CountryId = new Guid("bc389b83-ded4-406a-a318-0616b7973734"),
                            Created = new DateTime(2019, 6, 28, 18, 39, 1, 25, DateTimeKind.Utc).AddTicks(6697),
                            CreatedBy = new Guid("fc3f9472-69c9-4dd3-8fab-8ba2639812f0"),
                            Inactive = false,
                            Name = "Karnataka",
                            Updated = new DateTime(2019, 6, 28, 18, 39, 1, 25, DateTimeKind.Utc).AddTicks(7035),
                            UpdatedBy = new Guid("fc3f9472-69c9-4dd3-8fab-8ba2639812f0")
                        });
                });

            modelBuilder.Entity("FaciTech.Apartment.Database.Models.SubArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AreaId");

                    b.Property<string>("Comments");

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("CreatedBy");

                    b.Property<bool>("Inactive");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("Updated");

                    b.Property<Guid>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("SubArea");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ea0cdc88-7fbd-4306-9bdf-a62d82a42d56"),
                            AreaId = new Guid("f314122a-e758-4c11-a48e-198ef276874e"),
                            Created = new DateTime(2019, 6, 28, 18, 39, 1, 26, DateTimeKind.Utc).AddTicks(2379),
                            CreatedBy = new Guid("fc3f9472-69c9-4dd3-8fab-8ba2639812f0"),
                            Inactive = false,
                            Name = "Jayanagar",
                            Updated = new DateTime(2019, 6, 28, 18, 39, 1, 26, DateTimeKind.Utc).AddTicks(2709),
                            UpdatedBy = new Guid("fc3f9472-69c9-4dd3-8fab-8ba2639812f0")
                        },
                        new
                        {
                            Id = new Guid("ddbdf5e0-f83f-4d72-af2a-1a64e6d0f338"),
                            AreaId = new Guid("538a9be1-25c0-4a26-a8dd-93e32937faa2"),
                            Created = new DateTime(2019, 6, 28, 18, 39, 1, 26, DateTimeKind.Utc).AddTicks(3356),
                            CreatedBy = new Guid("fc3f9472-69c9-4dd3-8fab-8ba2639812f0"),
                            Inactive = false,
                            Name = "Hebbal",
                            Updated = new DateTime(2019, 6, 28, 18, 39, 1, 26, DateTimeKind.Utc).AddTicks(3361),
                            UpdatedBy = new Guid("fc3f9472-69c9-4dd3-8fab-8ba2639812f0")
                        });
                });

            modelBuilder.Entity("FaciTech.Apartment.Database.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comments");

                    b.Property<Guid>("ContactId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("CreatedBy");

                    b.Property<bool>("Inactive");

                    b.Property<bool>("Primary");

                    b.Property<Guid>("UnitId");

                    b.Property<DateTime>("Updated");

                    b.Property<Guid>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("UnitId");

                    b.ToTable("Tenant");
                });

            modelBuilder.Entity("FaciTech.Apartment.Database.Models.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comments");

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("CreatedBy");

                    b.Property<int>("FloorNumber");

                    b.Property<bool>("Inactive");

                    b.Property<string>("Number")
                        .IsRequired();

                    b.Property<Guid>("OwnerContactId");

                    b.Property<Guid>("OwnerId");

                    b.Property<Guid>("SectionId");

                    b.Property<string>("Specification");

                    b.Property<DateTime>("Updated");

                    b.Property<Guid>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("SectionId");

                    b.ToTable("Unit");
                });

            modelBuilder.Entity("FaciTech.Apartment.Database.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comments");

                    b.Property<Guid?>("ContactId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("CreatedBy");

                    b.Property<bool>("Inactive");

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Salt")
                        .IsRequired();

                    b.Property<DateTime>("Updated");

                    b.Property<Guid>("UpdatedBy");

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fc3f9472-69c9-4dd3-8fab-8ba2639812f0"),
                            Comments = "sys user record",
                            Created = new DateTime(2019, 6, 28, 18, 39, 1, 24, DateTimeKind.Utc).AddTicks(9396),
                            CreatedBy = new Guid("fc3f9472-69c9-4dd3-8fab-8ba2639812f0"),
                            Inactive = false,
                            Password = "Bi4Fi6tHEiF+Cv3Jh0V0MA==",
                            Salt = "123",
                            Updated = new DateTime(2019, 6, 28, 18, 39, 1, 25, DateTimeKind.Utc).AddTicks(54),
                            UpdatedBy = new Guid("fc3f9472-69c9-4dd3-8fab-8ba2639812f0"),
                            Username = "system"
                        });
                });

            modelBuilder.Entity("FaciTech.Apartment.Database.Models.UserGroup", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("GroupId");

                    b.Property<string>("Comments");

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("CreatedBy");

                    b.Property<bool>("Inactive");

                    b.Property<DateTime>("Updated");

                    b.Property<Guid>("UpdatedBy");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("UserGroup");
                });

            modelBuilder.Entity("FaciTech.Apartment.Database.Models.Area", b =>
                {
                    b.HasOne("FaciTech.Apartment.Database.Models.City", "City")
                        .WithMany("Areas")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FaciTech.Apartment.Database.Models.City", b =>
                {
                    b.HasOne("FaciTech.Apartment.Database.Models.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FaciTech.Apartment.Database.Models.Community", b =>
                {
                    b.HasOne("FaciTech.Apartment.Database.Models.SubArea", "SubArea")
                        .WithMany("Communities")
                        .HasForeignKey("SubAreaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FaciTech.Apartment.Database.Models.GroupRole", b =>
                {
                    b.HasOne("FaciTech.Apartment.Database.Models.Group", "Group")
                        .WithMany("GroupRoles")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FaciTech.Apartment.Database.Models.Role", "Role")
                        .WithMany("GroupRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FaciTech.Apartment.Database.Models.RoleFeature", b =>
                {
                    b.HasOne("FaciTech.Apartment.Database.Models.Feature", "Feature")
                        .WithMany("RoleFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FaciTech.Apartment.Database.Models.Role", "Role")
                        .WithMany("RoleFeatures")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FaciTech.Apartment.Database.Models.Section", b =>
                {
                    b.HasOne("FaciTech.Apartment.Database.Models.Community", "Community")
                        .WithMany("Sections")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FaciTech.Apartment.Database.Models.State", b =>
                {
                    b.HasOne("FaciTech.Apartment.Database.Models.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FaciTech.Apartment.Database.Models.SubArea", b =>
                {
                    b.HasOne("FaciTech.Apartment.Database.Models.Area", "Area")
                        .WithMany("SubAreas")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FaciTech.Apartment.Database.Models.Tenant", b =>
                {
                    b.HasOne("FaciTech.Apartment.Database.Models.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FaciTech.Apartment.Database.Models.Unit", "Unit")
                        .WithMany("Tenants")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FaciTech.Apartment.Database.Models.Unit", b =>
                {
                    b.HasOne("FaciTech.Apartment.Database.Models.Contact", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FaciTech.Apartment.Database.Models.Section", "Section")
                        .WithMany("Units")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FaciTech.Apartment.Database.Models.User", b =>
                {
                    b.HasOne("FaciTech.Apartment.Database.Models.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId");
                });

            modelBuilder.Entity("FaciTech.Apartment.Database.Models.UserGroup", b =>
                {
                    b.HasOne("FaciTech.Apartment.Database.Models.Group", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FaciTech.Apartment.Database.Models.User", "User")
                        .WithMany("UserGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
